services:
  php:
    build:
      context: ./docker/php
      args:
        PHP_VERSION: 8.4.1
#    image: naegato/php-symfony:php8.4.1-postgres
    volumes:
      - .:/srv:cached
    depends_on:
      - db

  web:
    build:
      context: ./docker/nginx
    volumes:
      - .:/srv:cached
    environment:
      fastcgi_pass: php:9000
    depends_on:
      - php

  db:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    environment:
      - POSTGRES_DB=schoolmanager
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=schoolmanager
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  node:
    image: node:23-alpine
    volumes:
      - .:/srv:cached
    working_dir: /srv
    command: tail -f /dev/null

#  mailbox:
#    image: dockage/mailcatcher

#  adminer:
#    image: adminer:4.8.1

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Comment the following line to enable HTTPS,
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8000
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  db_data:
  mercure_data:
  mercure_config:
